kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: voting-app
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30004
        hostPort: 30004
        listenAddress: "0.0.0.0"
      - containerPort: 30005
        hostPort: 30005
        listenAddress: "0.0.0.0"
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
